### ISSUE TITLE
Posting to twtxt.txt in picoblog?

### ISSUE THREAD

**Issue by sorenpeter** [hxii/picoblog#1]
Hey, this look really nice.

Is there a way to post to the twtxt.txt in picoblog?
I had a look at the code but could not see anything about it.

/sørenpeter

**Comment by hxii** [comment]
Hey sørenpeter, glad you like Picoblog.
Did you by any chance mean https://twtxt.net/ ? If so then unfortunately not currently.
That being said, Picoblog essentially uses the same format, so I guess support could be implemented.

**Comment by sorenpeter** [comment]
Hi, no i did't mean twtxt.net although I have been messing around with it for quite a bit the last couple of days.
I got my own twtxt.txt at my own domain and was looking for way to post to it.

I read on your blog that picoblog got an API for writing to it, but did't know to make it work.
So for the I have been coding a selfhosted form in php to post to my own twtxt.txt, that I will be putting on github soon.

**Comment by hxii** [comment]
@sorenpeter Please note this is nowhere near done 😂
https://0xff.nu/picoblog-api

**Comment by sorenpeter** [comment]
Looks more advanced than what I made:
http://darch.dk/phpub2twtxt

**Comment by hxii** [comment]
It's a learning experience for both of us then :)
But yeah, like I've mentioned the main goal of Picoblog was to be a self-hosted microblog. I've yet to properly implement TWTXT support with how it works.
