### ISSUE TITLE
Sorting the order of post when using twtxt-style?

### ISSUE THREAD

**Issue by sorenpeter** [hxii/picoblog#2]
Hey,

I can see within picoblog.php, that there are what looks like a way to sort posts by newest or oldest, but how do I make use of it? I have set picoblog up at http://darch.dk/twtxt

Thanks,
SørenPeter

**Comment by hxii** [comment]
Hey! I've added sorting in the last commit: https://github.com/hxii/picoblog/commit/08676d5dea31b65a63943ab1af57320f9bf71a67
Currently, you can only reverse the entry array (which is valid for `all`, `id` and `tag` values of $search in `getEntries()`).

**Comment by sorenpeter** [comment]
Thank you,

Can you give an example of how it will look in the URL?

**Comment by hxii** [comment]
@sorenpeter It's not a query (although can be easily supported) but rather code.
E.g. https://github.com/hxii/picoblog/blob/master/blog.php#L11
Here you can use `$mb->getEntries('all', true)` to get all the entries in reverse.
In the context (and format) of Picoblog, this would mean that you will get the entries from oldest to newest.
