### ISSUE TITLE
Using an external txt file does not work.

### ISSUE THREAD

**Issue by sorenpeter** [hxii/picoblog#3]
Hi,

When I try to use an external txt file picoblog just gives me a blank screen:
`$mb = new \hxii\PicoBlog('http://twtxt.net/user/darch/twtxt.txt');`

/Søren Peter

**Comment by hxii** [comment]
Hey, thanks for the report!
Resolved by https://github.com/hxii/picoblog/commit/aa1c5473c89f24c9f4716c2650efcc5523d75d58
